# Dockerfile for React client

### STAGE 1: Build ###
# Build react client
FROM node:12 AS client

# Working directory be app
WORKDIR /usr/src/app
COPY package*.json ./

###  Installing dependencies
RUN npm install --silent

# copy local files to app folder
COPY . .

### STAGE 2: Production Environment ###
RUN npm run build
FROM nginx:1.19
COPY --from=client /usr/src/app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]