name: NodeJS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Test Client Side
      working-directory: ./client
      uses: actions/setup-node@v2
      with:
        node-version: 12.x
        persist-credentials: false
    - run: sudo npm ci
    - run: sudo npm run build


    - name: Test Server Side
      working-directory: ./server 
      uses: actions/setup-node@v2
      with:
        node-version: 12.x
    - run: sudo npm ci
    - run: sudo npm run server
