# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.18.3
      uses: actions/setup-node@v2
      with:
        node-version: 12.18.3
    - run: npm --prefix /client ci
    - run: npm --prefix /client run server
    - run: npm --prefix /client run build
    - run: npm --prefix /server ci
    - run: npm --prefix /server ci
    - run: npm --prefix /server run server

