name: NodeJS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Test Client Side
      uses: actions/setup-node@v2
      with:
        node-version: 12.x
    - run: npm --prefix /client cache clean --force
    - run: sudo npm --prefix /client ci 
    - run: sudo npm --prefix /client run build


    - name: Test Server Side
      uses: actions/setup-node@v2
      with:
        node-version: 12.x
    - run: sudo npm --prefix /client cache clean --force
    - run: sudo npm --prefix /server ci 
    - run: sudo npm --prefix /server run server

