name: NodeJS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

    - name: Test Client Side
      working-directory: ./client
    - run: sudo npm ci
    - run: sudo npm run build


    - name: Test Server Side
      working-directory: ./server
    - run: sudo npm ci
    - run: sudo npm run server
